version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourPassword
      MYSQL_DATABASE: BUDGET
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
volumes:
  db_data: {}
